### ISSUE TITLE
No longer working on latest betterdiscord version 1.13.

### ISSUE THREAD

**Issue by sull324** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#64]
Title say it all,love the addons but unfortunaly since the latest betterdiscord change it doesnt load anymore.

**Comment by RoguedBear** [comment]
Can you let me know what has broken? 

I just updated my Discord client and betterdiscord client, i can see settings page is working, status is changing.
```md
## Discord Info
Stable 474172 (05f9404)
Host 1.0.9216 x64 (72385)
Windows 11 64-bit (10.0.26100)

## BetterDiscord
Stable 1.13.0 (539e2e6)

### 3 Plugins (1 Enabled):
- ZeresPluginLibrary
- AutoIdleOnAFK (Enabled)
- BetterAnimations

### 0 Themes (0 Enabled):


```

**Comment by sull324** [comment]
sorry,i took an look this morning and have more details.

TypeError: BdApi.loadData is not a function 


so i replaced 

BdApi.loadData(
BdApi.saveData(
BdApi.deleteData(
 
with

BdApi.Data.load(
BdApi.Data.save(
BdApi.Data.delete(

and it load fine,i havent checked if its working correctly as im actively using discord right now.

but thank you for taking the time to answer the ticket

**Comment by RoguedBear** [comment]
can you confirm the plugin version? These functions were deprecated by BD quite a while back and they were updated in this plugin in version `0.5.1` in pr #62

**Comment by sull324** [comment]
omg,you are so right -_-,my plugins never updated.I am so sorry for wasting your time. thanks for taking the time.

I will close the ticket now.

**Comment by RoguedBear** [comment]
Ah, no worries mate! It wasn't a bother for me. 
Feels good knowing once in a while someone out there is still using this plugin ;)
